CREATE TABLE IF NOT EXISTS tables(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  location_id BIGINT UNSIGNED NOT NULL,
  
  table_number INT UNSIGNED NOT NULL,
  occupants INT UNSIGNED NOT NULL DEFAULT 4,
  status ENUM ('open', 'occupied', 'reserved') DEFAULT 'open',

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),

  FOREIGN KEY (location_id) REFERENCES locations (id)
);