CREATE TABLE IF NOT EXISTS house_order_items(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  house_order_id BIGINT UNSIGNED NOT NULL,
  menu_item_id BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  price DECIMAL(10, 2) UNSIGNED NOT NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),

  FOREIGN KEY (house_order_id) REFERENCES house_orders(id),
  FOREIGN KEY (menu_item_id) REFERENCES menu_items(id)
);